name: Build, Test, and Deploy

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "23.1.0"

      # 의존성 설치 및 테스트 실행
      - name: Install Dependencies
        run: yarn install

      - name: Run Tests
        run: yarn test
